config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/dashboard'
  post '/posts/create', to: 'posts#create', as: 'posts'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord


    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true

    before_save :replace_word

    def replace_word
        self.content = self.content.gsub! "spoiler", ""
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard

  def index
    @posts = Post.order(id: :desc)
  end

  def dashboard
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)

    if @post.save(post_params)
    else
      render :create
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :image_url, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
<div class="inner bg-warning ">
    <ul class="copyright">
        <li>&copy; <%= Time.now.year %>. All rights reserved</li>
    </ul>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning ">
   <%= link_to 'Sumbarino Amarillo', posts_index_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', posts_index_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Dashboard', posts_dashboard_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- copiar el stylesheet aquí-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!--Aquí va el JS pop y query-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


 
  <body>
    <%= render partial:'/layouts/navbar' %>
    <div class="wrapper style2">
			<article id="main" class="container special">
				<p>
					<%= yield %>
				</p>
			</article>
		</div>
    <%= render partial:'/layouts/footer' %>
  </body>
     
        
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/create.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2>
      prohibited this post from being saved:
    </h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <h1> Te registraste con éxito </h1>
<% end %>

app/views/posts/dashboard.html.erb
<h2> Nuevo Artículo </h2>
<form id="create_posts" method="post" action="/posts/create">
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <p>
    <%= form.label "Título" %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label "URL de la imagen"%><br>
    <%= form.text_field :image_url %>
  </p>
 
  <p>
    <%= form.label "Contenido"%><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit "Guardar" %>
  </p>
<% end %>
</form>

app/views/posts/index.html.erb
<h1 class="text-primary">{ Posts }</h1>

<table class="table">
  <tr>
    <th>Titulo</th>
    <th>Fecha de ingreso</>
    <th>Contenido</th>
    <th>Imagen</th>
  </tr>   

<% @posts.each do |post|%>

<tr>
    <td><%=post.title%></td>
    <td><%=post.created_at.strftime("%F")%></td>
    <td><%=post.image_url%></td>
    <td><%=post.content%></td>
</tr>

<%end%>
</table>